### ISSUE TITLE
Enforcing the "schema"

### ISSUE THREAD

**Issue by eykamp** [ramazanpolat/prodict#10]
Now that I implemented the change for Issue #3, and you accepted the PR, I'm going to make an argument why it may be the wrong solution to the wrong problem.

On the plus side, behavior between `obj["key"]` and `obj.key` is now consistent.  That's good.

On the minus side, you still have some surprising behavior.

Take the example:

    from prodict import Prodict
    from typing import Optional

    class Car(Prodict):
        brand: str
        year: int
        color: Optional[str]    # Using Optional to indicate None is a legitimate value here

    honda = Car.from_dict({"brand": "Honda", "year": "2020"})
    print(honda)  

This prints `{'brand': 'Honda', 'year': 2020}`

But... I would argue that what you really want to print is: `{'brand': 'Honda', 'year': 2020, 'color': None}`

And using the code above, `honda.texture = "rough"` works, even though `texture` is not part of the "schema" you defined in the Car class.  I think that assignment should raise an exception (but `honda.color = "red"` should continue to work).

Finally, with the code change in Issue #3, `honda.color` raises a KeyError, whereas I think it should return None (but `honda.protein` should continue to raise a KeyError because `protein` is not part of the "schema".

I have code that addresses all these issues, and lets you use your type declarations as a mostly enforceable schema.  If you agree, I can make a PR.

**Comment by ramazanpolat** [comment]
Good point. 

>And using the code above, honda.texture = "rough" works, even though texture is not part of the "schema" you defined in the Car class. I think that assignment should raise an exception (but honda.color = "red" should continue to work).

Assigning a new attribute dynamically is a design goal for `Prodict` since you can do the same with `dict`.
So `honda.texture = "rough"` should work without raising an exception. Of course we can make it raise exception but this is not the intended behaviour.

>Finally, with the code change in Issue #3, honda.color raises a KeyError, whereas I think it should return None (but honda.protein should continue to raise a KeyError because protein is not part of the "schema".

I also thought if `honda.color` should return `None` or raise KeyError. Both options seem fine. Right now, using `honda.protein` on righ-hand side already returns KeyError if you didn't set it to some value before. Meaning:
```py
print(honda.protein) # KeyError
honda.protein = 'X' # works.
print(honda.protein) # prints 'X'
```

> I have code that addresses all these issues, and lets you use your type declarations as a mostly enforceable schema. If you agree, I can make a PR.

In prodict, attributes defined as type hints are **not a strict schema** of the class. There are good alternatives that use strict shema like [Pydantic](https://github.com/samuelcolvin/pydantic/) and [python dataclasses](url). So here `Prodict` is trying to have similar behavior to regular dict. I admire the work you put in `Prodict` but enforceable schema thing is not suitable for `Prodict` because this will make it a Pydantic clone with less features.

**Comment by eykamp** [comment]
> Assigning a new attribute dynamically is a design goal for Prodict

That's fine... it's your design, after all.  I've implemented my stricter version by subclassing prodict, and I can move forward with that design.  And if assignment works, then retrieval should obviously work, as with the protein example you provided.

The reason I opened this as an issue rather than submitting a PR was that I thought you might want to keep things working the way they are.

**Comment by ramazanpolat** [comment]
@eykamp I would like to see your stricter version if I may. Just to look how you made it and learn from it. Do you have it in a repo?

**Comment by eykamp** [comment]
I might still have it, but it was not an ideal solution.  After some experimentation, we ended up switching to pydantic, which does something similar to prodict but with a different emphasis and a very sophisticated type management system.  Pydantic uses native type hints at runtime to serialize/deserialize complex objects to/from json (something I did not know was possible), resulting in very readable and maintainable code.

If I can find my work on prodict (it's on a machine I don't have access to at the moment), I'll post it somewhere so you can have a look.

**Comment by ramazanpolat** [comment]
That's why I recommended Pydantic over stricter Prodict :)

**Comment by eykamp** [comment]
It was a good suggestion.  You seemed to know what I was looking for better than I did!
