### ISSUE TITLE
New Bug after updating to 0.8.15 --  'undefined_key' error

### ISSUE THREAD

**Issue by cfeied** [ramazanpolat/prodict#19]
The readme for Prodict gives this example, which used to work but now fails:

```
a = dict(my_key=1)
print(a['my_key']) # 1
print(a['undefined_key']) # KeyError: 'undefined_key'

p = Prodict(my_key=1)
print(p.my_key) # 1
# print(p.undefined_key]) # erroneous right bracket in example must be removed
print(p.undefined_key) # None
```
The error is this:

```
>>> p = Prodict(my_key=1)
>>> print(p.undefined_key) # Expected None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Python37_64\lib\site-packages\prodict\__init__.py", line 240, in __getattr__
    return self[item]
KeyError: 'undefined_key'
```

**Comment by ramazanpolat** [comment]
My apologies. I forgot to update the README, which I updated now.

Since `Prodict` imitates regular python `dict`, we had to decide what to do if the key does not exist.
In the first implementation, we decided to return `None`, if the object does not have that key.

So this contradicted with the regular `dict` behavior. Therefore we changed that behavior to raise `KeyError`.

If you want it to return `None` for non-existent keys, then you should use `.get` method, just like regular `dict`:

```py
p = Prodict(a=42)
print(p.undefined_key) # Raises KeyError
print(p.get(undefined_key, None) # returns None
print(p.get(undefined_key, 'DEFAULT_VALUE') # returns 'DEFAULT_VALUE'
```

I'm thinking about making this optional but any property that is defined on the object as a flag to set this behavior will need this setting to be stored on the object itself, which in turn will manipulate the `dict` content inadvertently. So I'm trying to figure out some other methods to make this behavior optional.

Right now, to get `None` for non-existent keys, your only choice is to use `.get(key,None)` method.

Sorry for any inconvenience you experienced because of this change.

**Comment by cfeied** [comment]
Thanks very much for the clarification. 

In thinking about this, it occurs to me that Prodict already behaves differently from dict in so many ways that I'm not sure consistency with dict is the best guiderail. For example, dict throws a KeyError when setting the value for a nonexistent key, while Prodict behaves like defaultdict in this instance.  

Perhaps when instantiating prodict we could specify whether we want *full* defaultdict behaviour (no KeyError on setting or retrieving a nonexistent key) or *half* defaultdict behaviour (KeyError on retrieving, but not on setting). 

I'm pretty sure that in no case do we want full compatibility with dict (KeyError when setting a nonexistent key and when retrieving one). :)
