### ISSUE TITLE
Prodict get() with default values.

### ISSUE THREAD

**Issue by andrewmellinger** [ramazanpolat/prodict#27]
Greetings!

If I do a "get" on a Prodict that has a value that was uninitialized the get still things it was "there" and it fails to return the default. 

So:
```
#! /usr/bin/env python3

from prodict import Prodict

class User(Prodict):
    user_id: int
    name: str

user = User.from_dict({"name": "Takara"})
print(f"User_id: '{user.get('user_id', 1138)}' was expecting '1138'")
```

Obviously, I can work around with default values, etc. but this has bitten me a couple times converting my code from raw dict usage to Prodict or accidentally passing a Prodict in to code that used to work.

Thanks!

**Comment by ramazanpolat** [comment]
This is the accepted behavior of Prodict (see #3) because if a key is defined, it has to have a value. We decided to make it this way so it will be easier to use. We could certainly add a toggle or something like that but Prodict is designed to be easy and intuitive to use. For more advanced features, I suggest you check [pydantic](https://github.com/samuelcolvin/pydantic) which is a great library and has more features but is also much stricter.

One quick workaround is to create the class with `Prodict.from_dict()` which won't set the defined keys to None. This will have some side effects like giving up the auto-type conversion but all other features will work fine:

```py
    from prodict import Prodict

    class User(Prodict):
        user_id: int
        name: str

    user: User = Prodict.from_dict({"name": "Takara"})

    print(f"User_id: '{user.get('user_id', 1138)}' was expecting '1138'")
```
> User_id: '1138' was expecting '1138'
